# Generated by Django 3.2.12 on 2024-03-19 13:56

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20240318_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='freeWritte',
            new_name='freeWrite',
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(datetime.date.today),
            preserve_default=False,
        ),
    ]
