# Generated by Django 4.2.4 on 2024-03-19 19:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20240318_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='freeWritte',
            new_name='freeWrite',
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=datetime.date.today)),
                ('mood_check', models.CharField(max_length=100)),
                ('sleep_check', models.CharField(max_length=100)),
                ('eating_check', models.CharField(max_length=100)),
                ('exercise_check', models.CharField(max_length=100)),
                ('journal_entry', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
