# Generated by Django 3.2.12 on 2024-03-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20240320_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyPrompts',
            new_name='DailyPrompt',
        ),
    ]
