# Generated by Django 3.2.12 on 2024-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20240319_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(),
        ),
    ]
