# Generated by Django 3.2.12 on 2024-03-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_dailyprompts_dailyprompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprompt',
            name='date',
        ),
    ]
