# Generated by Django 3.2.12 on 2024-03-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_freewritte_journal_freewrite_and_more'),
        ('main_app', '0004_alter_dailycheckin_date'),
    ]

    operations = [
    ]
