# Generated by Django 4.2.11 on 2024-03-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_journal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload_photo/'),
        ),
    ]
