# Generated by Django 4.2.11 on 2024-03-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_dailysummary_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysummary',
            name='user_photo',
        ),
    ]
