# Generated by Django 4.2.4 on 2024-03-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20240321_1819'),
        ('main_app', '0008_remove_dailysummary_user_photo'),
    ]

    operations = [
    ]
