# Generated by Django 4.2.4 on 2024-03-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20240321_1844'),
        ('main_app', '0009_merge_20240321_1849'),
    ]

    operations = [
    ]
