# Generated by Django 3.2.12 on 2024-03-22 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_dailycheckin_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
